/* ════════════════════════════════════════════
   온라인 학습지 데이터 파일  v2.2.3
   버전 관리: 2.[학습지추가].[오류수정]
   ════════════════════════════════════════════ */
const WS_VERSION = "2.2.4";

const UNITS = [
  { id:"u1-01", title:"소인수분해",            grade:1, category:"수와 연산" },
  { id:"u1-02", title:"정수와 유리수",          grade:1, category:"수와 연산" },
  { id:"u1-03", title:"문자와 식",              grade:1, category:"변화와 관계" },
  { id:"u1-04", title:"일차방정식",             grade:1, category:"변화와 관계" },
  { id:"u1-05", title:"좌표평면과 그래프",       grade:1, category:"변화와 관계" },
  { id:"u1-06", title:"기본 도형",              grade:1, category:"도형과 측정" },
  { id:"u1-06b",title:"작도와 합동",            grade:1, category:"도형과 측정" },
  { id:"u1-07", title:"평면도형의 성질",         grade:1, category:"도형과 측정" },
  { id:"u1-08", title:"입체도형의 성질",         grade:1, category:"도형과 측정" },
  { id:"u1-09", title:"대푯값",                 grade:1, category:"자료와 가능성" },
  { id:"u1-10", title:"도수분포표와 상대도수",   grade:1, category:"자료와 가능성" },
  { id:"u2-01", title:"유리수와 순환소수",       grade:2, category:"수와 연산" },
  { id:"u2-02", title:"다항식의 계산",         grade:2, category:"변화와 관계" },
  { id:"u2-03", title:"일차부등식",             grade:2, category:"변화와 관계" },
  { id:"u2-04", title:"연립일차방정식",          grade:2, category:"변화와 관계" },
  { id:"u2-05", title:"일차함수와 그래프",        grade:2, category:"변화와 관계" },
  { id:"u2-06", title:"일차함수와 일차방정식",   grade:2, category:"변화와 관계" },
  { id:"u2-07", title:"삼각형의 성질",          grade:2, category:"도형과 측정" },
  { id:"u2-08", title:"사각형의 성질",          grade:2, category:"도형과 측정" },
  { id:"u2-09", title:"도형의 닮음",            grade:2, category:"도형과 측정" },
  { id:"u2-09b",title:"피타고라스 정리",         grade:2, category:"도형과 측정" },
  { id:"u2-10", title:"경우의 수",              grade:2, category:"자료와 가능성" },
  { id:"u2-11", title:"확률",                   grade:2, category:"자료와 가능성" },
  { id:"u3-01", title:"제곱근과 실수",          grade:3, category:"수와 연산" },
  { id:"u3-02", title:"다항식의 곱셈과 인수분해", grade:3, category:"변화와 관계" },
  { id:"u3-03", title:"이차방정식",             grade:3, category:"변화와 관계" },
  { id:"u3-04", title:"이차함수와 그래프",        grade:3, category:"변화와 관계" },
  { id:"u3-05", title:"삼각비",                grade:3, category:"도형과 측정" },
  { id:"u3-06", title:"원의 성질",             grade:3, category:"도형과 측정" },
  { id:"u3-07", title:"산포도",                grade:3, category:"자료와 가능성" },
  { id:"u3-08", title:"상자그림과 산포도",       grade:3, category:"자료와 가능성" },
];

/* ── 2022 개정 교육과정 중학교 수학 단원 ── */
const WORKSHEETS = [
  // 1학년
  { id:"m1-01", title:"소인수분해",            grade:1, category:"수와 연산",    questions:[] },
  { id:"m1-02", title:"정수와 유리수",          grade:1, category:"수와 연산",    questions:[] },

  // ── 소인수분해 용어 학습 ──────────────────────────────
  { id:"ws-v1-01", title:"VOCA(소인수분해)", type:"vocab", unitId:"u1-01", diff:1,
    vocab:[
      { term:"소수",       def:"1보다 큰 자연수 중 약수가 1과 자기 자신뿐인 수" },
      { term:"합성수",     def:"소수가 아닌 1보다 큰 자연수" },
      { term:"밑",         def:"거듭제곱에서 반복하여 곱하는 수" },
      { term:"지수",       def:"거듭제곱에서 밑을 곱한 횟수" },
      { term:"소인수",     def:"어떤 자연수의 인수 중 소수인 것" },
      { term:"소인수분해", def:"자연수를 소인수만의 곱으로 나타내는 것" },
    ],
    extras:[
      { type:"find_prime"          },
      { type:"find_non_prime"      },
      { type:"find_prime_factor"   },
      { type:"find_non_prime_factor" },
    ]
  },

  // ── 정수와 유리수 용어 학습 ───────────────────────────
  { id:"ws-v1-02", title:"VOCA(정수와 유리수)", type:"vocab", unitId:"u1-02", diff:1,
    extras:[
      { type:"find_positive"       },
      { type:"find_negative"       },
      { type:"find_pos_int"        },
      { type:"find_neg_int"        },
      { type:"find_non_int_rat"    },
    ],
    vocab:[
      { term:"양수",     def:"0보다 큰 수" },
      { term:"음수",     def:"0보다 작은 수" },
      { term:"정수",     def:"양의 정수(자연수), 0, 음의 정수를 통틀어 이르는 말" },
      { term:"유리수",   def:"분수 \\(\\frac{m}{n}\\) (m, n은 정수, n≠0) 꼴로 나타낼 수 있는 수" },
      { term:"절댓값",   def:"수직선 위에서 원점으로부터 어떤 수까지의 거리" },
      { term:"교환법칙", def:"두 수의 자리를 바꾸어 계산해도 결과가 같은 성질" },
      { term:"결합법칙", def:"세 수를 계산할 때 어느 두 수를 먼저 계산해도 결과가 같은 성질" },
      { term:"분배법칙", def:"어떤 수를 두 수의 합(차)에 곱한 것은 각각 곱한 것의 합(차)과 같은 성질" },
    ]
  },

  // ── 문자와 식 (학습지 없음, 추후 추가)
  // { id:"ws-u1-03-01", unitId:"u1-03", title:"문자와 식 연습문제1", grade:1, questions:[] },
  // ── 문자와 식 (다항식의 계산)
  { id:"ws-u1-03-01", unitId:"u1-03",
    title:"다항식의 계산", grade:1, category:"변화와 관계",
    bookPage:"",
    questions:[
      // ── 1단계: 분배법칙 개념 ──
      { id:"q00a", type:"word", answerType:"text",
        text:"다음과 같은 계산 법칙을 무엇이라고 하는가?<br>\\(a(b + c) = ab + ac\\)",
        answer:"분배법칙", answerAlt:["분배 법칙"], diff:1 },
      // ── 1단계: 1차식 × 상수 ──
      { id:"q01", type:"word", answerType:"expr",
        text:"\\(3(2x + 4)\\)를 계산하시오.",
        answer:"6x+12", answerAlt:[], diff:1 },
      { id:"q02", type:"word", answerType:"expr",
        text:"\\(-2(3x - 5)\\)를 계산하시오.",
        answer:"-6x+10", answerAlt:["−6x+10"], diff:1 },
      { id:"q03", type:"word", answerType:"expr",
        text:"\\(4(-x + 3)\\)을 계산하시오.",
        answer:"-4x+12", answerAlt:["−4x+12"], diff:1 },
      { id:"q04", type:"word", answerType:"expr",
        text:"\\(\\frac{1}{2}(4x-6)\\)을 계산하시오.",
        answer:"2x-3", answerAlt:["2x−3"], diff:1 },
      // ── 2단계: 동류항 개념 ──
      { id:"q00b", type:"word", answerType:"text",
        text:"다항식에서 _____와 _____가 각각 같은 항을 <strong style=\"color:var(--accent)\">\"동류항\"</strong>이라고 한다.<br>(두 빈칸에 들어갈 말을 쉼표로 구분지어 적으세요. 예: 사과, 배)",
        answer:"문자, 차수", answerAlt:["차수, 문자","문자,차수","차수,문자","곱해진 문자, 차수","차수, 곱해진 문자"], diff:1 },
      // ── 2단계: 동류항 찾기 (multi) ──
      { id:"q05", type:"multi",
        text:"\\(3x\\)의 동류항을 모두 고르시오.",
        options:["5x","2y","−x","7","4x²","x/2","−3x","0.5x","2x²","6y"],
        answer:[0,2,5,6,7], diff:2 },
      { id:"q06", type:"multi",
        text:"\\(-2x^2\\)의 동류항을 모두 고르시오.",
        options:["x²","3x","−5x²","4x²y","2x²","−x","7x²","x²/2","−3y","6"],
        answer:[0,2,4,6,7], diff:2 },
      { id:"q07", type:"multi",
        text:"\\(4 (\\)상수항)의 동류항을 모두 고르시오.",
        options:["3x","−7","2x²","5","0","1/2","3xy","−3","8x","2"],
        answer:[1,3,4,5,7,9], diff:2 },
      { id:"q08", type:"multi",
        text:"\\(-3xy\\)의 동류항을 모두 고르시오.",
        options:["2xy","x","−y","5xy","xy/2","3x²y","−xy","4y","7xy","−2x"],
        answer:[0,3,4,6,8], diff:2 },
      // ── 3단계: 괄호 개념 ──
      { id:"q00c", type:"word", answerType:"text",
        text:"다항식의 덧셈과 뺄셈은 _____끼리만 계산한다.<br>\\((\\)빈칸에 들어갈 말을 쓰시오.)",
        answer:"동류항", answerAlt:[], diff:1 },
      // ── 3단계: (ax+b) ± (cx+d) ──
      { id:"q09", type:"word", answerType:"expr",
        text:"\\((3x + 5) + (2x - 3)\\)을 계산하시오.",
        answer:"5x+2", answerAlt:[], diff:2 },
      { id:"q10", type:"word", answerType:"expr",
        text:"\\((4x - 1) + (-x + 3)\\)을 계산하시오.",
        answer:"3x+2", answerAlt:[], diff:2 },
      { id:"q11", type:"word", answerType:"expr",
        text:"\\((2x + 3) - (x - 4)\\)를 계산하시오.",
        answer:"x+7", answerAlt:[], diff:2 },
      { id:"q12", type:"word", answerType:"expr",
        text:"\\(\\left(\\frac{3}{4}x+1\\right)-\\left(\\frac{1}{4}x-2\\right)\\)를 계산하시오.",
        answer:"1/2x+3", answerAlt:["x/2+3"], diff:3 },
      // ── 4단계: a(bx+c) + d(ex+f) ──
      { id:"q13", type:"word", answerType:"expr",
        text:"\\(2(3x + 1) + 3(x - 2)\\)를 계산하시오.",
        answer:"9x-4", answerAlt:[], diff:3 },
      { id:"q14", type:"word", answerType:"expr",
        text:"\\(3(2x - 1) - 2(x + 3)\\)을 계산하시오.",
        answer:"4x-9", answerAlt:[], diff:3 },
      { id:"q15", type:"word", answerType:"expr",
        text:"\\(4(x + 2) - 3(2x - 1)\\)을 계산하시오.",
        answer:"-2x+11", answerAlt:[], diff:3 },
      { id:"q16", type:"word", answerType:"expr",
        text:"\\(\\frac{1}{2}(4x-2)+\\frac{1}{3}(6x+9)\\)를 계산하시오.",
        answer:"4x+2", answerAlt:[], diff:4 },
    ]
  },

  // ── 일차방정식
  // ── 문자와 식 중단원 연습문제

  // ── 문자와 식 용어 학습 ──────────────────────────────
  { id:"ws-v1-03", title:"VOCA(문자와 식)", type:"vocab", unitId:"u1-03", diff:1,
    extras:[
      { type:"find_poly"     },
      { type:"find_non_poly" },
      { type:"find_deg1"     },
      { type:"find_deg2"     },
      { type:"find_deg3"     },
      { type:"find_deg4"     },
    ],
    vocab:[
      { term:"항",     def:"수 또는 문자의 곱으로 이루어진 식" },
      { term:"상수항", def:"수로만 이루어진 항" },
      { term:"계수",   def:"항에서 문자에 곱해진 수" },
      { term:"차수",   def:"어떤 항에서 문자가 곱해진 횟수" },
      { term:"단항식", def:"하나의 항으로만 이루어진 식" },
      { term:"다항식", def:"한 개 이상의 항의 합으로 이루어진 식" },
      { term:"동류항", def:"문자와 차수가 각각 같은 항" },
    ]
  },

  { id:"ws-u1-03-02", unitId:"u1-03",
    title:"중단원 연습문제", grade:1, category:"변화와 관계",
    bookPage:"",
    questions:[
      // ── 1번: 문장을 식으로 ──
      { id:"q01a", type:"word", answerType:"text", diff:1,
        text:"다음을 문자를 사용해 식으로 나타내시오.<br>(1) \\(x\\)의 3배에서 \\(y\\)의 4배를 뺀 값",
        answer:"3x-4y", answerAlt:["3x−4y"] },
      { id:"q01b", type:"word", answerType:"text", diff:1,
        text:"다음을 문자를 사용해 식으로 나타내시오.<br>(2) 하루에 500원씩 \\(x\\)일 동안 모아 5900원짜리 카네이션을 샀을 때 남은 금액",
        answer:"500x-5900", answerAlt:["500x−5900"] },
      // ── 2번: 기호 생략 ──
      { id:"q02a", type:"word", answerType:"text", diff:1,
        text:"다음 식을 곱셈 기호 ×와 나눗셈 기호 ÷를 생략하여 간단히 나타내시오.<br>(1) \\(4\\times a\\times a\\)",
        answer:"4a²", answerAlt:["4a^2"] },
      { id:"q02b", type:"word", answerType:"text", diff:1,
        text:"(2) \\(-11\\div b\\)",
        answer:"-11/b", answerAlt:["−11/b","−11÷b 생략"] },
      { id:"q02c", type:"word", answerType:"text", diff:1,
        text:"(3) \\(3\\times a\\div2\\)",
        answer:"3a/2", answerAlt:["3a÷2 생략"] },
      { id:"q02d", type:"word", answerType:"text", diff:2,
        text:"(4) \\(-1\\times (x+y)\\div a\\)",
        answer:"-(x+y)/a", answerAlt:["−(x+y)/a"] },
      // ── 3번: 식의 값 ──
      { id:"q03a", type:"equation", diff:2,
        text:"\\(x=3,\ y=-4\\)일 때, 다음 식의 값을 구하시오.<br>(1) \\(2x+y\\)", answer:2 },
      { id:"q03b", type:"equation", diff:2,
        text:"(2) \\(\\frac{1}{3}x+\\frac{1}{2}y\\)", answer:-1 },
      { id:"q03c", type:"equation", diff:2,
        text:"(3) \\(5(x+y)\\)", answer:-5 },
      { id:"q03d", type:"equation", diff:3,
        text:"(4) \\(x^2+y^2\\)", answer:25 },
      // ── 4번: 계수와 상수항 ──
      { id:"q04a", type:"equation", diff:2,
        text:"다항식 \\(-4x+y-5\\)에서 \\(x\\)의 계수를 구하시오.", answer:-4 },
      { id:"q04b", type:"equation", diff:2,
        text:"다항식 \\(-4x+y-5\\)에서 \\(y\\)의 계수를 구하시오.", answer:1 },
      { id:"q04c", type:"equation", diff:2,
        text:"다항식 \\(-4x+y-5\\)에서 상수항을 구하시오.", answer:-5 },
      // ── 5번: 단항식 계산 ──
      { id:"q05a", type:"word", answerType:"expr", diff:1,
        text:"다음을 계산하시오.<br>(1) \\(5a\\times 3\\)",
        answer:"15*a", answerAlt:["15a"] },
      { id:"q05b", type:"word", answerType:"expr", diff:1,
        text:"(2) \\(8b\\div4\\)",
        answer:"2*b", answerAlt:["2b"] },
      { id:"q05c", type:"word", answerType:"expr", diff:2,
        text:"(3) \\(4(-3x+1)\\)",
        answer:"-12*x+4", answerAlt:["-12x+4","4-12*x","4-12x"] },
      // ── 6번: 동류항 계산 ──
      { id:"q06a", type:"word", answerType:"expr", diff:1,
        text:"다음을 계산하시오.<br>(1) \\(6a+3a\\)",
        answer:"9*a", answerAlt:["9a"] },
      { id:"q06b", type:"word", answerType:"expr", diff:1,
        text:"(2) \\(4x+7x\\)",
        answer:"11*x", answerAlt:["11x"] },
      { id:"q06c", type:"word", answerType:"expr", diff:1,
        text:"(3) \\(7y-2y\\)",
        answer:"5*y", answerAlt:["5y"] },
      // ── 7번: 도형 넓이 ──
      { id:"q07a", type:"word", answerType:"expr", diff:2,
        text:`다음과 같은 도형의 넓이를 문자를 사용해 식으로 나타내시오.<br>(1) 사다리꼴 (윗변 a, 아랫변 b, 높이 h)<br><img src="images/ws-u1-03-02-q07a.png" style="display:block;max-width:220px;width:100%;margin:8px auto" alt="사다리꼴">`,
        answer:"(a+b)*h/2", answerAlt:["(a+b)/2*h","h*(a+b)/2","1/2*(a+b)*h"] },
      { id:"q07b", type:"word", answerType:"expr", diff:2,
        text:`(2) 마름모 (두 대각선 \\(x\\), \\(y\\))<br><img src="images/ws-u1-03-02-q07b.png" style="display:block;max-width:150px;width:100%;margin:8px auto" alt="마름모">`,
        answer:"x*y/2", answerAlt:["x*y*1/2","1/2*x*y","y*x/2"] },
      // ── 8번: 목장 둘레 ──
      { id:"q08", type:"word", answerType:"expr", diff:3,
        text:`완두는 오른쪽 그림과 같은 목장 둘레에 울타리를 만들려고 한다. 전체 울타리의 길이를 \\(a\\), \\(b\\)에 대한 식으로 나타내시오.<br><img src="images/ws-u1-03-02-q08.png" style="display:block;max-width:260px;width:100%;margin:8px 0" alt="목장">`,
        answer:"2*a+2*b+12", answerAlt:["2*(a+b+6)","2a+2b+12","2(a+b+6)"] },
      // ── 9번: 다항식 계산 ──
      { id:"q09a", type:"word", answerType:"expr", diff:2,
        text:"다음을 계산하시오.<br>(1) \\((4a+5b)+(-7a+4b)\\)",
        answer:"-3*a+9*b", answerAlt:["-3a+9b","9b-3a","9*b-3*a"] },
      { id:"q09b", type:"word", answerType:"expr", diff:2,
        text:"(2) \\((-3a+b)-(a+2b)\\)",
        answer:"-4*a-b", answerAlt:["-4a-b","-(4*a+b)","-(4a+b)"] },
      { id:"q09c", type:"word", answerType:"expr", diff:3,
        text:"(3) \\((4x-y)+3(2x+y)\\)",
        answer:"10*x+2*y", answerAlt:["10x+2y","2*y+10*x","2y+10x"] },
      { id:"q09d", type:"word", answerType:"expr", diff:3,
        text:"(4) \\(3(2x+3y)+\\frac{1}{3}(-4x+2y)\\)",
        answer:"4*x+10*y", answerAlt:["4x+10y","10*y+4*x","10y+4x"] },
      // ── 10번: A-2B 계산 ──
      { id:"q10", type:"word", answerType:"expr", diff:3,
        text:"\\(A=4x+2y, B=3x-y\\)일 때, \\(A-2B\\)를 계산하시오.",
        answer:"-2*x+4*y", answerAlt:["-2x+4y","4*y-2*x","4y-2x"] },
      // ── 11번: 번개 거리 ──
      { id:"q11", type:"equation", diff:3,
        text:"기온이 \\(x\\)°C일 때, 소리의 속도는 초속 \\(331.5+0.6x\\) m이다. 기온이 25°C일 때, 나루는 번개를 보고 3초 후 천둥소리를 들었다. 나루가 번개 친 곳으로부터 떨어진 거리를 구하시오. (m)",
        answer:1039.5 },
      // ── 12번: 마방진 ──
      { id:"q12a", type:"word", answerType:"text", diff:4,
        text:`다음 표에서 가로, 세로, 대각선에 있는 식들의 합이 모두 같도록 빈칸을 채우시오.<br>(1) 빈칸 5개를 행 순서대로 쉼표로 입력하시오.<br>(가운데행 □□□, 아래행 □ □ 순서)<br><table style="border-collapse:collapse;margin-top:8px"><tr><td style="border:1.5px solid #6b7280;padding:6px 10px;text-align:center;font-family:'Courier New',monospace;font-size:14px;min-width:52px">\\(-5x\\)</td><td style="border:1.5px solid #6b7280;padding:6px 10px;text-align:center;font-family:'Courier New',monospace;font-size:14px;min-width:52px">\\(5x\\)</td><td style="border:1.5px solid #6b7280;padding:6px 10px;text-align:center;font-family:'Courier New',monospace;font-size:14px;min-width:52px">\\(3x\\)</td></tr><tr><td style="border:1.5px solid #6b7280;padding:6px 10px;text-align:center;font-family:'Courier New',monospace;font-size:14px;min-width:52px;background:#fef9c3;color:#92400e;font-weight:700">□</td><td style="border:1.5px solid #6b7280;padding:6px 10px;text-align:center;font-family:'Courier New',monospace;font-size:14px;min-width:52px;background:#fef9c3;color:#92400e;font-weight:700">□</td><td style="border:1.5px solid #6b7280;padding:6px 10px;text-align:center;font-family:'Courier New',monospace;font-size:14px;min-width:52px;background:#fef9c3;color:#92400e;font-weight:700">□</td></tr><tr><td style="border:1.5px solid #6b7280;padding:6px 10px;text-align:center;font-family:'Courier New',monospace;font-size:14px;min-width:52px;background:#fef9c3;color:#92400e;font-weight:700">□</td><td style="border:1.5px solid #6b7280;padding:6px 10px;text-align:center;font-family:'Courier New',monospace;font-size:14px;min-width:52px">\\(-3x\\)</td><td style="border:1.5px solid #6b7280;padding:6px 10px;text-align:center;font-family:'Courier New',monospace;font-size:14px;min-width:52px;background:#fef9c3;color:#92400e;font-weight:700">□</td></tr></table>`,
        answer:"9x, x, -7x, -x, 7x", answerAlt:["9x,x,-7x,-x,7x"] },
      { id:"q12b", type:"word", answerType:"text", diff:4,
        text:`(2) 빈칸 5개를 위치 순서대로 쉼표로 입력하시오.<br>(위3, 중1, 중3, 아래1, 아래3 순서)<br><table style="border-collapse:collapse;margin-top:8px"><tr><td style="border:1.5px solid #6b7280;padding:6px 10px;text-align:center;font-family:'Courier New',monospace;font-size:14px;min-width:52px">\\(-2a\\)</td><td style="border:1.5px solid #6b7280;padding:6px 10px;text-align:center;font-family:'Courier New',monospace;font-size:14px;min-width:52px">\\(3a+5\\)</td><td style="border:1.5px solid #6b7280;padding:6px 10px;text-align:center;font-family:'Courier New',monospace;font-size:14px;min-width:52px;background:#fef9c3;color:#92400e;font-weight:700">□</td></tr><tr><td style="border:1.5px solid #6b7280;padding:6px 10px;text-align:center;font-family:'Courier New',monospace;font-size:14px;min-width:52px;background:#fef9c3;color:#92400e;font-weight:700">□</td><td style="border:1.5px solid #6b7280;padding:6px 10px;text-align:center;font-family:'Courier New',monospace;font-size:14px;min-width:52px">\\(a+1\\)</td><td style="border:1.5px solid #6b7280;padding:6px 10px;text-align:center;font-family:'Courier New',monospace;font-size:14px;min-width:52px;background:#fef9c3;color:#92400e;font-weight:700">□</td></tr><tr><td style="border:1.5px solid #6b7280;padding:6px 10px;text-align:center;font-family:'Courier New',monospace;font-size:14px;min-width:52px;background:#fef9c3;color:#92400e;font-weight:700">□</td><td style="border:1.5px solid #6b7280;padding:6px 10px;text-align:center;font-family:'Courier New',monospace;font-size:14px;min-width:52px">\\(-a-3\\)</td><td style="border:1.5px solid #6b7280;padding:6px 10px;text-align:center;font-family:'Courier New',monospace;font-size:14px;min-width:52px;background:#fef9c3;color:#92400e;font-weight:700">□</td></tr></table>`,
        answer:"2a-2, 5a-1, -3a+3, 4, 4a+2", answerAlt:["2a-2,5a-1,-3a+3,4,4a+2","2a−2, 5a−1, −3a+3, 4, 4a+2"] },
    ]
  },

  { id:"ws-u1-04-01", unitId:"u1-04",
    title:"일차방정식 연습문제1", grade:1, category:"변화와 관계", bookPage:"80~86",
    questions:[
    { id:"q01", text:"\\(3x = 12\\)",                                   answer:4,  diff:1 },
    { id:"q02", text:"\\(2x + 1 = 7\\)",                                answer:3,  diff:1 },
    { id:"q03", text:"\\(5x - 3 = 2x + 9\\)",                          answer:4,  diff:2 },
    { id:"q04", text:"\\(4(x - 1) = 2x + 6\\)",                        answer:5,  diff:2 },
    { id:"q05", text:"\\(2(x + 3) = 3(x - 1)\\)",                      answer:9,  diff:2 },
    { id:"q06", text:"\\(0.3x - 0.7 = 0.2x + 0.5\\)",                  answer:12, diff:3 },
    { id:"q07", text:"\\(\\frac{x}{2} + 1 = \\frac{x}{3} + 2\\)",                        answer:6,  diff:3 },
    { id:"q08", text:"\\(\\frac{x - 1}{3} = \\frac{x + 2}{4}\\)",                    answer:10, diff:3 },
    { id:"q09", text:"\\(3(2x - 1) - 2(x + 4) = x - 3\\)",            answer:8/3, answerFrac:"8/3", diff:4 },
    { id:"q10", text:"\\(0.5(x + 4) = 0.2(x - 1) + 3.1\\)",           answer:3,  diff:4 },
    { id:"q11", text:"\\(\\frac{2x}{3} - 1 = \\frac{x}{2} + 1\\)",                       answer:12, diff:4 },
    { id:"q12", text:"\\(5(x - 2) - 3(2x - 1) = -7\\)",               answer:0,  diff:4 },
    { id:"q13", text:"\\(0.4(x + 5) = 0.6(x - 1) + 0.2\\)",           answer:12, diff:5 },
    { id:"q14", text:"\\(\\frac{3x - 1}{4} - \\frac{x + 2}{3} = 1\\)",              answer:23/5, answerFrac:"23/5", diff:5 },
  ]},
  { id:"ws-u1-04-02", unitId:"u1-04",
    title:"일차방정식 연습문제2", grade:1, category:"변화와 관계", bookPage:"87~90",
    questions:[
      // ── 유형A: 뜻 보고 용어 맞추기 ──
      { id:"q01", type:"word",
        text:"수 또는 문자의 곱으로 이루어진 식의 각 부분을 무엇이라고 하는가?",
        answer:"항", answerAlt:[], diff:1 },
      // ── 유형B: 용어 보고 빈칸 ──
      { id:"q02", type:"word",
        text:"\\(3x^2-5x+2\\)에서 항의 개수는?",
        answer:"3", answerAlt:[], diff:1 },
      { id:"q03", type:"word",
        text:"항에서 문자를 제외한 수 부분을 무엇이라고 하는가?",
        answer:"계수", answerAlt:[], diff:1 },
      { id:"q04", type:"word",
        text:"\\(-7x\\)에서 \\(x\\)의 계수는?",
        answer:"-7", answerAlt:["−7"], diff:1 },
      { id:"q05", type:"word",
        text:"문자 없이 수만으로 이루어진 항을 무엇이라고 하는가?",
        answer:"상수항", answerAlt:[], diff:1 },
      { id:"q06", type:"word",
        text:"\\(4x^3-2x+9\\)에서 상수항은?",
        answer:"9", answerAlt:[], diff:1 },
      { id:"q07", type:"word",
        text:"항에서 문자가 곱해진 횟수를 무엇이라고 하는가?",
        answer:"차수", answerAlt:[], diff:1 },
      { id:"q08", type:"word",
        text:"\\(3x^2\\)의 차수는?",
        answer:"2", answerAlt:[], diff:1 },
      { id:"q09", type:"word",
        text:"\\(a=b\\)이면 \\(a+3=b+□\\) (□에 들어갈 수는?)",
        answer:"3", answerAlt:[], diff:2 },
      { id:"q10", type:"word",
        text:"\\(a=b\\)이면 \\(2a=□b\\) (□에 들어갈 수는?)",
        answer:"2", answerAlt:[], diff:2 },
      { id:"q11", type:"word",
        text:"미지수의 값에 따라 참이 되기도 하고 거짓이 되기도 하는 등식을 무엇이라고 하는가?",
        answer:"방정식", answerAlt:[], diff:2 },
      { id:"q12", type:"word",
        text:"방정식을 참이 되게 하는 미지수의 값을 무엇이라고 하는가?",
        answer:"해", answerAlt:["근"], diff:2 },
      // ── 유형C: 일차방정식 풀기 (수식 입력) ──
      { id:"q13", type:"equation", text:"\\(x - 3 = 5\\)",                    answer:8,     answerFrac:null, diff:1 },
      { id:"q14", type:"equation", text:"\\(2x = -10\\)",                      answer:-5,    answerFrac:null, diff:1 },
      { id:"q15", type:"equation", text:"\\(3x + 4 = 13\\)",                   answer:3,     answerFrac:null, diff:2 },
      { id:"q16", type:"equation", text:"\\(2x + 1 = 3x - 2\\)",               answer:3,     answerFrac:null, diff:2 },
      { id:"q17", type:"equation", text:"\\(4(x + 2) = 3x + 11\\)",            answer:3,     answerFrac:null, diff:3 },
      { id:"q18", type:"equation", text:"\\(3x + 1 = 2x - \\frac{1}{2}\\)",             answer:-1.5,  answerFrac:"-3/2", diff:4 },
      { id:"q19", type:"equation", text:"\\(2x - 1 = x + \\frac{1}{3}\\)",              answer:4/3,   answerFrac:"4/3", diff:4 },
      { id:"q20", type:"equation", text:"\\(5(x - 1) - 3(x + 2) = -3\\)",      answer:4,     answerFrac:null, diff:3 },
    ]
  },
  { id:"ws-u1-04-03", unitId:"u1-04",
    title:"일차방정식의 활용1", grade:1, category:"변화와 관계",
    bookPage:"91~94",
    questions:[
      // ── 복습 A: 문자로 표현하기 ──
      { id:"q01", type:"word", answerType:"expr",
        text:"한 개에 800원인 사과 \\(x\\)개의 가격을 식으로 나타내면?",
        answer:"800x", answerAlt:["800*x","800×x"], diff:1 },
      { id:"q02", type:"word", answerType:"expr",
        text:"길이가 \\(a\\) cm인 리본을 4등분 했을 때 한 조각의 길이를 식으로 나타내면?",
        answer:"a/4", answerAlt:["a÷4"], diff:1 },
      { id:"q03", type:"word", answerType:"expr",
        text:"어떤 수 \\(x\\)에서 7을 뺀 수의 3배를 식으로 나타내면?",
        answer:"3(x-7)", answerAlt:["3(x−7)","(x-7)×3","(x−7)×3"], diff:1 },
      // ── 복습 B: 일차방정식 풀기 ──
      { id:"q04", type:"equation", text:"\\(6x - 2 = 4x + 8\\)",           answer:5,  diff:2 },
      { id:"q05", type:"equation", text:"\\(3(x + 4) = 5x - 2\\)",          answer:7,  diff:2 },
      { id:"q06", type:"equation", text:"\\(\\frac{x + 1}{2} = \\frac{x - 1}{3} + 1\\)", answer:1,  diff:3 },
      // ── 연습하기 (링크, 문항 번호 제외) ──
      { id:"연습하기", type:"link",
        text:"아래 링크에 접속해서 연습하고, 충분히 연습한 사람은 다음 문제로 넘어가세요.",
        linkUrl:"https://sites.google.com/snu-g.ms.kr/sentensce/%ED%99%88",
        linkLabel:"📖 문장제 문제 단계별 풀이",
        diff:1 },
      // ── 문장제 문제 ──
      { id:"q08", type:"equation",
        text:"연속하는 두 홀수의 합이 36일 때, 두 수 중 작은 수는?",
        answer:17, diff:2 },
      { id:"q09", type:"equation",
        text:"어떤 수의 2배에서 5를 빼면 그 수에 3을 더한 것과 같다. 어떤 수는?",
        answer:8, diff:2 },
      { id:"q10", type:"equation",
        text:"현재 어머니 나이는 41세, 딸 나이는 13세다. 어머니 나이가 딸 나이의 2배가 되는 것은 몇 년 후인가?",
        answer:15, diff:3 },
      { id:"q11", type:"equation",
        text:"가로가 세로보다 4 cm 긴 직사각형의 둘레가 32 cm일 때, 세로의 길이는 몇 cm인가?",
        answer:6, diff:3 },
      { id:"q12", type:"equation",
        text:"800원짜리 사탕과 1200원짜리 초콜릿을 합쳐 10개 사서 9600원을 냈다. 사탕의 개수는?",
        answer:6, diff:3 },
      { id:"q13", type:"equation",
        text:"형과 동생의 나이 합이 25세이고 형이 동생보다 3살 많다. 형의 나이는?",
        answer:14, diff:2 },
      { id:"q14", type:"equation",
        text:"50 km떨어진 두 지점에서 두 사람이 동시에 마주보고 걷는다. 속력이 각각 시속 3 km, 2 km일 때, 만나는 데 걸리는 시간은 몇 시간인가?",
        answer:10, diff:3 },
      { id:"q15", type:"equation",
        text:"물건을 정가의 20% 할인하여 팔았더니 4800원이었다. 정가는 몇 원인가?",
        answer:6000, diff:3 },
      { id:"q16", type:"equation",
        text:"학생들에게 공책을 4권씩 나눠 주면 7권이 남고, 5권씩 나눠 주면 8권이 부족하다. 학생 수는?",
        answer:15, diff:3 },
      { id:"q17", type:"equation",
        text:"둘레가 52 cm인 직각삼각형에서 빗변이 나머지 두 변의 합보다 6 cm 짧을 때, 빗변의 길이는 몇 cm인가?",
        answer:23, diff:4 },
    ]
  },
  { id:"m1-04", title:"좌표평면과 그래프",       grade:1, category:"변화와 관계",  questions:[] },
  { id:"m1-05", title:"기본 도형",              grade:1, category:"도형과 측정",  questions:[] },
  { id:"m1-06", title:"평면도형의 성질",         grade:1, category:"도형과 측정",  questions:[] },
  { id:"m1-07", title:"입체도형의 성질",         grade:1, category:"도형과 측정",  questions:[] },
  { id:"m1-08", title:"자료의 정리와 해석",      grade:1, category:"자료와 가능성", questions:[] },
  // 2학년
  { id:"m2-01", title:"유리수와 순환소수",       grade:2, category:"수와 연산",    questions:[] },
  { id:"m2-02", title:"단항식과 다항식",         grade:2, category:"변화와 관계",  questions:[] },
  { id:"m2-03", title:"일차부등식",             grade:2, category:"변화와 관계",  questions:[] },
  { id:"m2-04", title:"연립일차방정식",          grade:2, category:"변화와 관계",  questions:[] },
  { id:"m2-05", title:"일차함수와 그래프",        grade:2, category:"변화와 관계",  questions:[] },
  { id:"m2-06", title:"일차함수와 일차방정식",   grade:2, category:"변화와 관계",  questions:[] },
  { id:"m2-07", title:"삼각형의 성질",          grade:2, category:"도형과 측정",  questions:[] },
  { id:"m2-08", title:"사각형의 성질",          grade:2, category:"도형과 측정",  questions:[] },
  { id:"m2-09", title:"도형의 닮음",            grade:2, category:"도형과 측정",  questions:[] },
  { id:"m2-10", title:"경우의 수와 확률",        grade:2, category:"자료와 가능성", questions:[] },
  // 3학년
  { id:"m3-01", title:"제곱근과 실수",          grade:3, category:"수와 연산",    questions:[] },
  { id:"m3-02", title:"다항식의 곱셈과 인수분해", grade:3, category:"변화와 관계",  questions:[] },
  { id:"m3-03", title:"이차방정식",             grade:3, category:"변화와 관계",  questions:[] },
  { id:"m3-04", title:"이차함수와 그래프",        grade:3, category:"변화와 관계",  questions:[] },
  { id:"m3-05", title:"삼각비",                grade:3, category:"도형과 측정",  questions:[] },
  { id:"m3-06", title:"원의 성질",             grade:3, category:"도형과 측정",  questions:[] },
  { id:"m3-07", title:"통계 (대푯값과 산포도)", grade:3, category:"자료와 가능성", questions:[] },

  { id:"ws-u1-04-04", unitId:"u1-04",
    title:"일차방정식의 활용2", grade:1, category:"변화와 관계",
    bookPage:"95~100",
    questions:[
      { id:"q01", type:"step3",
        text:"연속하는 세 자연수의 합이 60이다. 가장 큰 수를 구하여라.",
        step1:{label:"방정식을 세우시오.", equation:"(x-1)+x+(x+1)=60", equationAlt:["x+(x+1)+(x+2)=60","(x-2)+(x-1)+x=60"]},
        step2:{label:"x의 값을 구하시오.", answer:20, hint:"x를 가운데 수로 놓을 때"},
        step3:{label:"가장 큰 수를 구하시오.", answer:"21", answerAlt:[], hint:"가장 큰 수 = x+1"},
        diff:1 },
      { id:"q02", type:"step3",
        text:"현재 아버지의 나이는 46세, 아들의 나이는 14세이다. 아버지의 나이가 아들의 나이의 3배가 되는 것은 몇 년 후인가?",
        step1:{label:"방정식을 세우시오.", equation:"46+x=3*(14+x)", equationAlt:["x+46=3*(x+14)","46+x=3(14+x)"]},
        step2:{label:"x의 값을 구하시오.", answer:2, hint:"x = 몇 년 후"},
        step3:{label:"몇 년 후인지 쓰시오. (단위 포함)", answer:"2년 후", answerAlt:["2년","2"], hint:"x = 2"},
        diff:1 },
      { id:"q03", type:"step3",
        text:"세 변의 길이의 비가 2:3:4인 삼각형의 둘레가 54cm이다. 가장 긴 변의 길이를 구하여라.",
        step1:{label:"방정식을 세우시오.", equation:"2*x+3*x+4*x=54", equationAlt:["2x+3x+4x=54","9x=54"]},
        step2:{label:"x의 값을 구하시오.", answer:6, hint:"x = 가장 짧은 변"},
        step3:{label:"가장 긴 변의 길이를 쓰시오. (단위 포함)", answer:"24cm", answerAlt:["24"], hint:"가장 긴 변 = 4x = 4×6"},
        diff:2 },
      { id:"q04", type:"step3",
        text:"700원짜리 연필과 1000원짜리 볼펜을 합쳐 10자루 사고 8200원을 냈다. 연필의 수를 구하여라.",
        step1:{label:"방정식을 세우시오.", equation:"700*x+1000*(10-x)=8200", equationAlt:["700x+1000(10-x)=8200"]},
        step2:{label:"x의 값을 구하시오.", answer:6, hint:"x = 연필의 수"},
        step3:{label:"연필의 수를 쓰시오. (단위 포함)", answer:"6자루", answerAlt:["6"], hint:"x = 6"},
        diff:2 },
      { id:"q05", type:"step3",
        text:"학생들에게 사탕을 6개씩 나누어 주면 4개가 남고, 7개씩 나누어 주면 6개가 부족하다. 학생 수를 구하여라.",
        step1:{label:"방정식을 세우시오.", equation:"6*x+4=7*x-6", equationAlt:["6x+4=7x-6"]},
        step2:{label:"x의 값을 구하시오.", answer:10, hint:"x = 학생 수"},
        step3:{label:"학생 수를 쓰시오. (단위 포함)", answer:"10명", answerAlt:["10"], hint:"x = 10"},
        diff:2 },
      { id:"q06", type:"equation", text:"어떤 수의 3배에서 5를 빼면 22이다. 어떤 수는?", answer:9, diff:2 },
      { id:"q07", type:"equation", text:"한 개에 500원인 사과를 x개 사고 5000원을 냈더니 1500원이 남았다. x는?", answer:7, diff:2 },
      { id:"q08", type:"equation", text:"가로가 세로보다 4cm 긴 직사각형의 둘레가 40cm이다. 세로의 길이는 몇 cm인가?", answer:8, diff:2 },
      { id:"q09", type:"equation", text:"연속하는 두 홀수의 합이 52이다. 두 수 중 큰 수는?", answer:27, diff:2 },
      { id:"q10", type:"equation", text:"학생들에게 연필을 4자루씩 나누어 주면 3자루가 남는다. 연필이 모두 27자루라면 학생 수는?", answer:6, diff:2 },
      { id:"q11", type:"equation", text:"어떤 수의 5배에서 3을 빼면 그 수의 2배에 9를 더한 것과 같다. 어떤 수는?", answer:4, diff:3 },
      { id:"q12", type:"equation", text:"형은 분속 60m, 동생은 분속 90m로 같은 방향으로 걷는다. 동생이 형보다 10분 늦게 출발했을 때, 동생이 형을 따라잡는 데 걸리는 시간은 몇 분인가?", answer:20, diff:3 },
      { id:"q13", type:"equation", text:"가로가 세로의 2배보다 3cm 짧은 직사각형의 둘레가 54cm이다. 세로의 길이는 몇 cm인가?", answer:10, diff:3 },
      { id:"q14", type:"equation", text:"800원짜리 음료수와 1200원짜리 과자를 합쳐 8개 사고 8000원을 냈다. 음료수의 개수는?", answer:4, diff:3 },
      { id:"q15", type:"equation", text:"학생들에게 공책을 5권씩 나누어 주면 4권이 남고, 7권씩 나누어 주면 6권이 부족하다. 학생 수는?", answer:5, diff:3 },
      { id:"q16", type:"equation", text:"어떤 일을 A 혼자 하면 12일, B 혼자 하면 6일 걸린다. A, B가 함께 2일 일하다가 B가 그만두고 A 혼자 나머지를 끝냈다. A가 혼자 일한 날수는?", answer:6, diff:4 },
      { id:"q17", type:"equation", text:"8%의 소금물 500g을 가열하여 물을 증발시켜 20%의 소금물을 만들었다. 증발시킨 물의 양은 몇 g인가?", answer:300, diff:4 },
      { id:"q18", type:"equation", text:"둘레가 300m인 트랙에서 A는 분속 90m, B는 분속 60m로 같은 방향으로 동시에 출발했다. A가 B를 3번째로 따라잡는 것은 출발 후 몇 분 후인가?", answer:30, diff:4 },
      { id:"q19", type:"equation", text:"A혼자 하면 18일, B 혼자 하면 9일 걸리는 일을 A가 혼자 3일 한 후 B와 함께 끝냈다. B와 함께 일한 날수는?", answer:5, diff:4 },
      { id:"q20", type:"equation", text:"10%의 소금물 300g에 소금을 더 넣어 25%의 소금물을 만들었다. 더 넣은 소금의 양은 몇 g인가?", answer:60, diff:4 },
    ]
  },

  // ── 일차방정식 중단원 마무리
  { id:"ws-u1-04-05", unitId:"u1-04",
    title:"중단원 마무리 문제", grade:1, category:"변화와 관계",
    bookPage:"",
    questions:[
      { id:"q01", type:"multi", diff:1,
        text:"다음 보기 중 방정식을 모두 찾으시오.",
        options:["ㄱ. 2x+4=6","ㄴ. x+2x−3x","ㄷ. 7>3−2","ㄹ. x/2+3=4"],
        answer:[0,3] },
      { id:"q02", type:"multi", diff:2,
        text:"다음 보기 중 항등식을 모두 찾으시오.",
        options:["ㄱ. 2x−x=x","ㄴ. 2x−2=0","ㄷ. −x−2=−(x+2)","ㄹ. \\(\\frac{1}{2}(x-4)=\\frac{1}{2}x-4\\)"],
        answer:[0,2] },
      { id:"q03", type:"multi", diff:2,
        text:"\\(a=b\\)일 때, 다음 중 옳은 것을 모두 고르시오.",
        options:["(1) a+2=b+2","(2) a−5=b+5","(3) 2a−3=2b−3","(4) \\(\\frac{a}{3}+4=\\frac{b}{4}+3\\)"],
        answer:[0,2] },
      { id:"q04", type:"word", answerType:"expr", diff:2,
        text:"다음 방정식에서 밑줄 친 항을 이항하시오.<br>(1) \\(3x\\underline{-6}=3\\)",
        answer:"6+3=3*x", answerAlt:["3*x=3+6","3*x=6+3","3x=3+6","3x=6+3"] },
      { id:"q04b", type:"word", answerType:"expr", diff:2,
        text:"다음 방정식에서 밑줄 친 항을 이항하시오.<br>(2) \\(4x=\\underline{-x}+5\\)",
        answer:"4*x+x=5", answerAlt:["4x+x=5"] },
      { id:"q04c", type:"word", answerType:"expr", diff:2,
        text:"다음 방정식에서 밑줄 친 항을 이항하시오.<br>(3) \\(x\\underline{-1}=\\underline{2x}+3\\)",
        answer:"x-2*x=3+1", answerAlt:["x-2x=3+1","-x=4","x-2*x=1+3"] },
      { id:"q04d", type:"word", answerType:"expr", diff:2,
        text:"다음 방정식에서 밑줄 친 항을 이항하시오.<br>(4) \\(3x\\underline{+2}=4\\underline{-x}\\)",
        answer:"3*x+x=4-2", answerAlt:["3x+x=4-2","4*x=4-2","4*x=2"] },
      { id:"q05", type:"equation", diff:2, text:"(1) \\(5x+2=3x+6\\)", answer:2 },
      { id:"q05b", type:"equation", diff:2, text:"(2) \\(2x+2=5x-7\\)", answer:3 },
      { id:"q06", type:"word", answerType:"expr", diff:2,
        text:"다음 문장을 등식으로 표현하여라.<br>(1) 초콜릿 70개를 \\(x\\)명에게 6개씩 나누어 주었더니 16개가 남았다.",
        answer:"6*x+16=70", answerAlt:["6x+16=70","70-6*x=16","70=6*x+16"] },
      { id:"q06b", type:"word", answerType:"expr", diff:2,
        text:"다음 문장을 등식으로 표현하여라.<br>(2) 한 개에 900원인 오렌지 \\(x\\)개와 한 개에 1500원인 사과 4개를 구매하고 12300원을 지불했다.",
        answer:"900*x+1500*4=12300", answerAlt:["900x+6000=12300","900*x+6000=12300"] },
        { id:"q07a", type:"word", answerType:"text", diff:2,
          text:`다음은 \\(-2x-6=4\\)를 등식의 성질을 이용해 푸는 과정이다.<br>\\(-2x-6+\\)<span style="border:1.5px solid #6b7280;padding:1px 5px;border-radius:2px;font-weight:700">(1)</span>\\(=4+\\)<span style="border:1.5px solid #6b7280;padding:1px 5px;border-radius:2px;font-weight:700">(1)</span><br>→ \\(-2x=10\\)<br>→ \\(x=\\)<span style="border:1.5px solid #6b7280;padding:1px 5px;border-radius:2px;font-weight:700">(2)</span><br><br><span style="border:1.5px solid #6b7280;padding:1px 5px;border-radius:2px;font-weight:700">(1)</span>과 <span style="border:1.5px solid #6b7280;padding:1px 5px;border-radius:2px;font-weight:700">(2)</span>에 들어갈 숫자를 차례대로 쓰시오.`,
          answer:"6,-5", answerAlt:["6, -5","6,−5","6, −5"] },
      { id:"q08", type:"equation", diff:3, text:"(1) \\(6(x-2)=4x\\)", answer:6 },
      { id:"q08b", type:"equation", diff:3, text:"(2) \\(-2(x-3)=3x+1\\)", answer:1 },
      { id:"q08c", type:"equation", diff:3, text:"(3) \\(0.1x-0.1=0.3x+0.5\\)", answer:-3 },
      { id:"q08d", type:"equation", diff:3,
        text:"다음 일차방정식을 풀어라.<br>(4) \\(-\\dfrac{x+1}{6}=\\dfrac{x+1}{3}-\\dfrac{1}{2}\\)",
        answer:0 },
      { id:"q09", type:"equation", diff:3,
        text:"일차방정식 \\(2(x-3)+10=ax\\)의 해가 \\(x=2\\)일 때, 수 \\(a\\)의 값을 구하시오.", answer:4 },
      { id:"q10", type:"equation", diff:3,
        text:"올해 완두의 어머니는 42살이고, 완두는 13살이다. 어머니의 나이가 완두 나이의 2배가 되는 때는 몇 년 후인지 구하시오.", answer:16 },
      { id:"q11", type:"equation", diff:3,
        text:"어느 달의 달력에서 자두가 태어난 날의 위쪽 날짜와 오른쪽 날짜를 더하면 22가 될 때, 자두의 생일을 구하시오.", answer:14 },
      { id:"q12a", type:"word", answerType:"text", diff:4,
        text:`오른쪽 그림과 같은 평면도에서 조건을 만족하도록 집을 설계한다.<br>① 방 1의 넓이는 주방의 넓이의 2배이다.<br>② 주방의 넓이는 화장실의 넓이의 4배이다.<br>③ 거실의 둘레의 길이는 30 m이다.<img src="images/ws-u1-04-05-q12a.png" style="display:block;max-width:260px;width:100%;margin:8px 0" alt="평면도"><br>(1) 화장실의 세로의 길이를 x에 대한 식으로 나타내시오.`,
        answer:"x", answerAlt:["xm","x m"] },
      { id:"q12b", type:"equation", diff:4,
        text:"\\((2) x\\)의 값을 구하시오.", answer:3 },
    ]
  },
];

// 모듈 환경에서도 접근 가능하도록 전역 할당
window.UNITS = UNITS;
window.WORKSHEETS = WORKSHEETS;
